form_app/urls.py
# login_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.form_view, name='formulario_aspirante'),  # Ruta principal del formulario
    path('registrar/', views.form_view, name='registrar_aspirante'),  # Registro del aspirante
    path('confirmacion/<int:aspirante_id>/', views.confirmacion, name='confirmacion'),
]

modulo_coordinador/urls.py
from django.urls import path
from . import views

app_name = 'coordinador_home'
urlpatterns = [
    path('home_coordinador/', views.empleado_view, name='home_coordinador'),  
    path('aspirante_dashboard/', views.dashboard_aspirantes_ec, name='dashboard_aspirante'),
    path('aspirante_detalles/<int:aspirante_id>/', views.detalles_aspirante, name='detalles_aspirante'),
    path('actualizar_status_ajax/<int:aspirante_id>/', views.ajax_aspirante_status, name='actualizar_status_ajax'),
    path('crear_usuario_ajax/', views.crear_usuario_ajax, name='crear_usuario_ajax'),
    path('aspirante_rechazado/', views.dashboard_aspirantes_rechazados, name='dashboard_aspirante_rechazado'),
    path('aspirante_aceptado/', views.dashboard_aspirantes_aceptados, name='dashboard_aspirante_aceptado'),
    path('aspirante_dashboard_eca_ecar/', views.dashboard_aspirantes_eca_ecar, name='dashboard_aspirante_eca_ecar'),
    path('aspirante_aceptado_eca_ecar/', views.dashboard_aspirantes_aceptados_eca_ecar, name='dashboard_aspirante_aceptado_eca_ecar'),
    path('aspirante_rechazado_eca_ecar/', views.dashboard_aspirantes_rechazados_eca_ecar, name='dashboard_aspirante_rechazado_eca_ecar'),
    path('dashboard/figura/educativas/', views.dashboard_figura_educativa, name='dashboard_figura_educativa'),
    path('detalles_educador/<int:empleado_id>/', views.detalles_educador, name='detalles_educador'),
    path('vacantes/dashboard/ct', views.dashboard_vacantes_ct, name='dashboard_vacantes_ct'),
    #aq
    path('asignar/vacantes', views.dashboard_asignar, name='asignar_dashboard'),
    path('vacantes/dashboards/asignacion_vacantes/<int:servicio_id>/', views.asignacion_vacantes_view_ct, name='asignacion_vacantes_ct'),
    path('observacion/exitosa', views.exito_view_ct, name='view_exito_ct'),
    #reportes
    path('menu/reportes', views.menu_reportes_ct, name='menu_reportes_ct'),
    path('dashboard/equipamiento', views.dashboard_equipamiento, name='dashboard_equipamiento'),
    path('dashboard/capacitacion/', views.dashboard_capacitacion_pdf, name='dashboard_capacitacion_pdf'),
    path('dashboard/seguimiento/', views.dashboard_seguim_pdf, name='dashboard_seguim_pdf'),
    path('reporte/<int:reporte_id>/validar-rechazar', views.validar_rechazar_reporte, name='validar_rechazar_reporte'),
    #GIS
    path('gestion_RMR/dashboard/ct', views.dashboard_gestion_RMR, name='gestion_RMR_dashboard_ct'),
    path('gestion_estado/dashboard/ct', views.dashboard_gestion_estado, name='estado_estado'),
    #CONVENIOS
    path('dashboard/convenios/', views.dashboard_convenio_view, name='dashboard_convenios'),
    path('convenio/<int:convenio_id>/actualizar-estado/', 
         views.actualizar_estado_convenio, 
         name='actualizar_estado_convenio'),
]
      

modulo_dot/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls.static import static  # Asegúrate de esta importación

app_name = 'dot_home'

urlpatterns = [
    path('home_dot/', views.home_view, name='home_dot'),
    path('agregar_usuario/', views.agregar_trabajador, name='home_agregar'),
    path('visualizar_dashboard/', views.dashboard_view, name='dashboard_visualizar'),
    path('detalles_empleado/<int:empleado_id>/', views.detalles_empleado, name='detalles_empleado'),
    path('modificar_dashboard/', views.modificar_dashboard, name='dashboard_modificar'),  # Configuración correcta
    path('empleado_modificar/<int:empleado_id>/', views.modificar_empleado, name='modificar_empleado'),
    path('dasboard/status/', views.status_empleado, name='dasboard_status'),
    path('ajax/empleado/status/<int:empleado_id>/', views.actualizar_status_ajax, name='actualizar_status_ajax'),
    path('dashboard/eliminar/', views.dashboard_eleminar, name='dashboard_eleminar'),
    path('eliminar/<int:empleado_id>/', views.eliminar_empleado, name='empleado_eliminar'),
    path('visualizacion/docs/', views.visualizar_docs, name='visualizacion_docs'),
    path('dashboard/vacantes/', views.dashboard_vacantes, name='dashboard_vacantes'),
    path('dashboard/convenios/', views.dashboard_convenios, name='dashboard_convenios'),
    path('guardar-firma/', views.save_signature, name='save_signature'),
    


]

web_conafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static

from django.conf import settings
from django.conf.urls.static import static


# Vista para redirigir a login
def redirect_to_login(request):
    return redirect("login")  # Redirige a la URL de login definida en 'login_app.urls'


urlpatterns = [

    path('capacitacion/', include('modulo_capacitacion.urls')),
    path('modulo_educadores/', include('modulo_educadores.urls')),

    path('modulo_pagos/', include('modulo_pagos.urls')),  # Incluye las rutas de modulo_pagos
    path('modulo_calendario/', include('modulo_calendario.urls')),  # Incluye las rutas de modulo_calendario

    path("admin/", admin.site.urls),
    path('modulo_DECB/', include('modulo_DECB.urls')),  # Incluye las rutas del módulo DECB
    path(
        "", redirect_to_login
    ),  # Redirige a la página de login cuando acceden a la raíz
    path('formulario_aspirante/', include('form_app.urls')),
    path("login/", include("login_app.urls")),  # Redirige a las URLs de login
    path('api/', include('modulo_dot.api_urls')),  # Rutas exclusivas de la API
    path(
        "dot_section/", include(("modulo_dot.urls", "dot_home"), namespace="dot_home")
    ),
    path(
        "empleado_section/",
        include(
            ("home_empleado.urls", "dashboard_empleado"), namespace="dashboard_empleado"
        ),
    ),
    path(
        "coordinador_section/",
        include(
            ("modulo_coordinador.urls", "coordinador_home"),
            namespace="coordinador_home",
        ),
    ),
    path(
        "apec_section/",
        include(("modulo_apec.urls", "modulo_apec"), namespace="modulo_apec"),
    ),
    path(
        "dpe_section/",
        include(
            ("modulo_dpe.urls", "modulo_dpe"), 
            namespace="modulo_dpe"),
    ),
]


# Servir archivos de medios durante el desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modulo_dot/models.py
import os
from django.db import models
from django.core.validators import FileExtensionValidator
from login_app.models import UsuarioRol  # Importa el modelo UsuarioRol de login_app
from login_app.models import Statuses  # Importa el modelo Statuses
from django.contrib.auth.hashers import make_password
from login_app.models import UsuarioRol  # Lo importamos localmente dentro de save
from modulo_apec.models import ApoyoGestion  # Importa el modelo ApoyoGestion de modulo_apec
from modulo_coordinador.models import ConveniosFiguras
from modulo_apec.models import ServicioEducativo  # Importa el modelo ServicioEducativo de modulo_apec
class Usuario(models.Model):
    usuario_rol = models.OneToOneField(UsuarioRol, null=True, blank=True, on_delete=models.CASCADE)
    usuario = models.CharField(max_length=255, unique=True, null=True, blank=True)
    contrasenia = models.CharField(max_length=255, null=True, blank=True)  # Contraseña en texto plano
    rol = models.CharField(
        max_length=10,
        choices=[  # Lista de roles
            ("CT", "Coordinador Territorial"),
            ("DECB", "Dirección de Educación Comunitaria e Inclusión Social"),
            ("DPE", "Dirección de Planeación y Evaluación"),
            ("EC", "Educador Comunitario"),
            ("ECA", "Educador Comunitario de Acompañamiento Microrregional"),
            ("ECAR", "Educador Comunitario de Acompañamiento Regional"),
            ("APEC", "Asesor de Promoción y Educación Comunitaria"),
            ("DOT", "Dirección de Operación Territorial"),
            ("ASPIRANTE", "aspirante"),
        ],
        default="ASPIRANTE",
    )

    def save(self, *args, **kwargs):
        # Validar solo si el rol no es "ASPIRANTE"
        if self.rol != "ASPIRANTE":
            if not self.usuario or not self.contrasenia:
                raise ValueError("Los campos 'usuario' y 'contrasenia' son obligatorios para roles distintos de 'ASPIRANTE'.")

        # Si el rol es "ASPIRANTE", no asignar username ni password
        if self.rol == "ASPIRANTE":
            self.usuario = None
            self.contrasenia = None
            if not self.usuario_rol:
                self.usuario_rol = UsuarioRol.objects.create(
                    username=None,
                    role=self.rol,
                    password=None,
                    is_active=False,
                )
        else:
            # Crear `usuario_rol` solo si no existe
            if not self.usuario_rol:
                self.usuario_rol = UsuarioRol.objects.create(
                    username=self.usuario,
                    role=self.rol,
                    password=make_password(self.contrasenia),
                )

        super().save(*args, **kwargs)

        # Llamamos a los métodos para gestionar el convenio, apoyo de gestión y estado
        self._handle_convenio()
        self._handle_apoyo_gestion()  
        self._handle_statuses()

    def _handle_convenio(self):
        """Gestiona la creación del objeto ConveniosFiguras basado en el estado del usuario."""
        if self.rol in ["ASPIRANTE", "EC", "ECA", "ECAR"]:
            # Comprobamos el último estado del usuario
            status = Statuses.objects.filter(usuario=self).order_by('-id').first()  # Último estado
            estado_convenio = 'Pendiente'  # Predeterminado

            if status:
                if status.status == 'suspendida':
                    estado_convenio = 'Pendiente'
                elif status.status == 'capacitacion':
                    estado_convenio = 'Aprobado'
                else:
                    estado_convenio = 'Rechazado'

            # Crear o actualizar el convenio con el estado evaluado
            convenio, created = ConveniosFiguras.objects.update_or_create(
                usuario=self,
                defaults={
                    'convenio_pdf': os.path.join('documentos', 'Convenio_figuras.pdf'),
                    'firma_digital': None,  # Firma digital puede ser añadida posteriormente
                    'estado_convenio': estado_convenio,
                    'firmado_por': None,
                },
            )

            if created:
                print(f"Convenio creado para el usuario {self.usuario} con estado {estado_convenio}")
            else:
                print(f"Convenio actualizado para el usuario {self.usuario} con estado {estado_convenio}")

    def _handle_statuses(self):
        """Gestiona la creación o actualización del estado del usuario según su rol."""
        if self.rol != "ASPIRANTE":
            # Si el rol es distinto a 'ASPIRANTE', se marca como 'activado'
            Statuses.objects.update_or_create(
                usuario=self,
                defaults={'status': 'activado'}
            )
        elif self.rol == "EC":
            # Si el rol es 'EC', se marca como 'capacitacion'
            Statuses.objects.update_or_create(
                usuario=self,
                defaults={'status': 'capacitacion'}
            )
        else:
            # Si el rol es 'ASPIRANTE' (o cualquier otro no mencionado antes), se marca como 'suspendido'
            Statuses.objects.update_or_create(
                usuario=self,
                defaults={'status': 'suspendido'}
            )

        # Asegurar que los convenios se actualicen acorde al estado
        self._handle_convenio()

    def _handle_apoyo_gestion(self):
        """Gestionar el apoyo de gestión para el rol 'EC' y crear ServicioEducativo asociado."""
        if self.rol == "EC":
            apoyo_gestion, created = ApoyoGestion.objects.update_or_create(
                usuario=self, 
                defaults={
                    'nombre_servicio_educativo': 'SERVICIO ED BASICA 22-2',  # Cambiar según corresponda
                    'numero_ec_asignado': 1,  # Ajustar según la lógica de negocio
                    'meses_servicio': 12,  # Ajustar según la lógica de negocio
                    'monto_apoyo_mensual': 6000,  # Establecer un valor predeterminado
                }
            )

            # Después de crear o actualizar el ApoyoGestion, recalculamos el presupuesto total
            if not created:
                # Si no es creado, recalculamos el presupuesto total
                apoyo_gestion.presupuesto_total_periodo = apoyo_gestion.calcular_presupuesto_total()
                apoyo_gestion.save()

    class Meta:
        db_table = "usuario"

    def __str__(self):
        return f"{self.usuario} - {self.rol}"


# Modelo de Datos Personales
class DatosPersonales(models.Model):
    nombre = models.CharField(max_length=255)
    apellidopa = models.CharField(max_length=255)
    apellidoma = models.CharField(max_length=255)
    edad = models.IntegerField()
    sexo = models.CharField(
        max_length=50,
        choices=[ 
            ("Masculino", "Masculino"),
            ("Femenino", "Femenino"),
            ("Otro", "Otro"),
        ],
    )
    correo = models.EmailField(unique=True)
    telefono = models.CharField(max_length=50)
    formacion_academica = models.CharField(max_length=255)
    curp = models.CharField(max_length=18, unique=True)
    fotografia = models.ImageField(
        upload_to="fotografias_personales/", null=True, blank=True
    )

    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)  # Relación OneToOne con Usuario

    def save(self, *args, **kwargs):
        # Asegurarse de que no existan datos personales asociados al usuario
        #if DatosPersonales.objects.filter(usuario=self.usuario).exists():
           # raise ValueError("Este usuario ya tiene datos personales asociados.")
        super().save(*args, **kwargs)

    class Meta:
        db_table = "datos_personales"

    def __str__(self):
        return f"{self.nombre} {self.apellidopa} {self.apellidoma}"


# Modelo de Documentos Personales
class DocumentosPersonales(models.Model):
    datos_personales = models.OneToOneField(
        "DatosPersonales",  # Usamos 'DatosPersonales' como referencia
        related_name="documentos",
        on_delete=models.CASCADE,
    )
    identificacion_oficial = models.FileField(
        upload_to="documentos_identificacion/",
        validators=[FileExtensionValidator(allowed_extensions=["pdf", "jpg", "png"])],
        null=True,  # Permite que el campo sea nulo
        blank=True,  # Permite que el campo esté vacío
    )
    comprobante_domicilio = models.FileField(
        upload_to="documentos_domicilio/",
        validators=[FileExtensionValidator(allowed_extensions=["pdf", "jpg", "png"])],
        null=True,  # Permite que el campo sea nulo
        blank=True,  # Permite que el campo esté vacío
    )
    certificado_estudio = models.FileField(
        upload_to="documentos_estudio/",
        validators=[FileExtensionValidator(allowed_extensions=["pdf", "jpg", "png"])],
        null=True,  # Permite que el campo sea nulo
        blank=True,  # Permite que el campo esté vacío
    )

    class Meta:
        db_table = "documentos_personales"
        verbose_name = "Documento Personal"
        verbose_name_plural = "Documentos Personales"

    def __str__(self):
        return f"Documentos de {self.datos_personales.nombre} {self.datos_personales.apellidopa}"

"""class DatosUsuario(models.Model):
    id_Datos = models.CharField(
        max_length=10,
        primary_key=True,
        verbose_name="Clave única del municipio",
    )
    nombreCompleto = models.CharField(max_length=255, unique=True, null=True, blank=True)
    id_comunidad = models.ForeignKey(
        'modulo_apec.Comunidad', on_delete=models.CASCADE, null=True, blank=True
    )
    situacion_Educativa = models.CharField(max_length=255, null=True, blank=True)
    tipoServicio = models.CharField(max_length=255, null=True, blank=True)
    contexto = models.CharField(max_length=255, null=True, blank=True)
    Estado = models.CharField(max_length=255, null=True, blank=True)
    class Meta:
        db_table = "datos_usuario"

    def __str__(self):

modulo_dot/templates/home_dot/actualizar_status.html
{% extends "base.html" %}

{% block title %}Actualizar Estado{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Actualizar Estado de {{ empleado.nombre }} {{ empleado.apellidopa }}</h2>

    {% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="status">Estado:</label>
            {{ form.status }}  <!-- Renderiza el campo del estado -->
        </div>
        <button type="submit" class="btn btn-success">Actualizar Estado</button>
    </form>

    <div class="mt-3">
        <a href="{% url 'dot_home:home_dot' %}" class="btn btn-warning">Volver al menú</a>
    </div>
</div>
{% endblock %}

modulo_dot/templates/home_dot/dot_home.html
{% extends "base.html" %}

{% block title %}Home Director{% endblock %}

{% block content %}
<div class="container mt-5">
  <h2 class="mb-4 text-center">Home Director</h2>
  <p class="text-center">Bienvenido Director!</p>
  <div class="row text-center">
    <!-- Botón Agregar -->
    <div class="col-md-4 mb-4">
      <a href="{% url 'dot_home:home_agregar' %}" class="btn btn-primary btn-block">
        <i class="fas fa-plus"></i> Agregar
      </a>
    </div>

    <!-- Botón Visualizar -->
    <div class="col-md-4 mb-4">
      <a href="{% url 'dot_home:dashboard_visualizar' %}" class="btn btn-primary btn-block">
        <i class="fas fa-eye"></i> Visualizar
      </a>
    </div>

    <!-- Botón Modificar -->
    <div class="col-md-4 mb-4">
      <a href="{% url 'dot_home:dashboard_modificar' %}" class="btn btn-warning btn-block">
        <i class="fas fa-edit"></i> Modificar
      </a>
    </div>

    <!-- Botón Status (nuevo formulario) -->
    <div class="col-md-4 mb-4">
      <a href="{% url 'dot_home:dasboard_status' %}" class="btn btn-success btn-block">
          <i class="fas fa-users"></i> Actualizar Status
      </a>
    </div>

    <!-- Botón Eliminar -->
    <div class="col-md-4 mb-4">
      <a href="{% url 'dot_home:dashboard_eleminar' %}" class="btn btn-danger btn-block">
        <i class="fas fa-trash"></i> Eliminar
      </a>
    </div>

    <!-- Botón Vacantes -->
    <div class="col-md-4 mb-4">
      <a href="{% url 'dot_home:dashboard_vacantes' %}" class="btn btn-info btn-block">
        <i class="fas fa-briefcase"></i> Vacantes
      </a>
    </div>
  </div>

  <!-- Fila para los botones Documentación y Convenios -->
  <div class="row justify-content-center">
    <!-- Botón Documentación -->
    <div class="col-md-4 mb-4">
      <a href="{% url 'dot_home:visualizacion_docs' %}" class="btn btn-secondary btn-block">
        <i class="fas fa-file-alt"></i> Documentación
      </a>
    </div>

    <!-- Botón Convenios -->
    <div class="col-md-4 mb-4">
      <a href="{% url 'dot_home:dashboard_convenios' %}" class="btn btn-secondary btn-block">
        <i class="fas fa-file-alt"></i> Convenios
      </a>
    </div>
  </div>

</div>
{% endblock %}

modulo_dot/templates/home_dot/home_agregar.html
{% extends "base.html" %}

{% block title %}Agregar Nuevo Usuario{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="d-flex justify-content-start mb-3">
    <a href="{% url 'dot_home:home_dot' %}" class="btn btn-warning" style="background-color: #620b0b; color:white">Menú</a>
  </div>

  <h2 class="text-center mb-4">Agregar Nuevo Usuario</h2>

  <!-- Bloque para mostrar los mensajes -->
  {% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
    </div>
  {% endif %}

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      <!-- Nombre del Usuario -->
      <div class="col-md-6 mb-3">
        <label for="id_nombre">Nombre</label>
        {{ datos_personales_form.nombre }}
        {% if datos_personales_form.nombre.errors %}
          <div class="alert alert-danger">
            {% for error in datos_personales_form.nombre.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- Apellido Paterno -->
      <div class="col-md-6 mb-3">
        <label for="id_apellidopa">Apellido Paterno</label>
        {{ datos_personales_form.apellidopa }}
        {% if datos_personales_form.apellidopa.errors %}
          <div class="alert alert-danger">
            {% for error in datos_personales_form.apellidopa.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- Apellido Materno -->
      <div class="col-md-6 mb-3">
        <label for="id_apellidoma">Apellido Materno</label>
        {{ datos_personales_form.apellidoma }}
        {% if datos_personales_form.apellidoma.errors %}
          <div class="alert alert-danger">
            {% for error in datos_personales_form.apellidoma.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- Correo Electrónico -->
      <div class="col-md-6 mb-3">
        <label for="id_correo">Email</label>
        {{ datos_personales_form.correo }}
        {% if datos_personales_form.correo.errors %}
          <div class="alert alert-danger">
            {% for error in datos_personales_form.correo.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- Teléfono -->
      <div class="col-md-6 mb-3">
        <label for="id_telefono">Teléfono</label>
        {{ datos_personales_form.telefono }}
        {% if datos_personales_form.telefono.errors %}
          <div class="alert alert-danger">
            {% for error in datos_personales_form.telefono.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- Edad -->
      <div class="col-md-6 mb-3">
        <label for="id_edad">Edad</label>
        {{ datos_personales_form.edad }}
        {% if datos_personales_form.edad.errors %}
          <div class="alert alert-danger">
            {% for error in datos_personales_form.edad.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

  <!-- Género -->
      <div class="col-md-6 mb-3">
          <label for="id_sexo">Género</label>
          <div class="form-check form-check-inline">
              {{ datos_personales_form.sexo }}
              {% if datos_personales_form.sexo.errors %}
                  <div class="alert alert-danger">
                      {% for error in datos_personales_form.sexo.errors %}
                          <p>{{ error }}</p>
                      {% endfor %}
                  </div>
              {% endif %}
          </div>
      </div>

      <!-- Formación Académica -->
      <div class="col-md-6 mb-3">
        <label for="id_formacion_academica">Formación Académica</label>
        {{ datos_personales_form.formacion_academica }}
        {% if datos_personales_form.formacion_academica.errors %}
          <div class="alert alert-danger">
            {% for error in datos_personales_form.formacion_academica.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- CURP -->
      <div class="col-md-6 mb-3">
        <label for="id_curp">CURP</label>
        {{ datos_personales_form.curp }}
        {% if datos_personales_form.curp.errors %}
          <div class="alert alert-danger">
            {% for error in datos_personales_form.curp.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- Foto -->
      <div class="col-md-6 mb-3">
        <label for="id_fotografia">Foto del Usuario</label>
        {{ datos_personales_form.fotografia }}
        {% if datos_personales_form.fotografia.errors %}
          <div class="alert alert-danger">
            {% for error in datos_personales_form.fotografia.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- Nombre de Usuario -->
      <div class="col-md-6 mb-3">
        <label for="id_usuario">Nombre de Usuario</label>
        {{ usuario_form.usuario }}
        {% if usuario_form.usuario.errors %}
          <div class="alert alert-danger">
            {% for error in usuario_form.usuario.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- Contraseña -->
      <div class="col-md-6 mb-3">
        <label for="id_contrasenia">Contraseña</label>
        {{ usuario_form.contrasenia }}
        {% if usuario_form.contrasenia.errors %}
          <div class="alert alert-danger">
            {% for error in usuario_form.contrasenia.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      
      <div class="col-md-6 mb-3">
        <label for="rol">Rol del Empleado</label>
        <select id="rol" name="rol" class="form-control" required>
          <option value="">Selecciona el Rol</option>
          <option value="DOT">Director de Operaciones y Tecnología</option>
          <option value="DECB">Dirección de Educación Comunitaria e Inclusión Social</option>
          <option value="DPE">Dirección de Planeación y Evaluación</option>
          <option value="CT">Coordinador Territorial</option>
          <option value="DEP">Dirección de Operación Territorial</option>
        </select>
      </div>

            <!-- Documentos Personales -->
      <div class="col-md-6 mb-3">
        <label for="id_identificacion_oficial">Identificación Oficial</label>
        {{ documentos_personales_form.identificacion_oficial }}
        {% if documentos_personales_form.identificacion_oficial.errors %}
          <div class="alert alert-danger">
            {% for error in documentos_personales_form.identificacion_oficial.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <div class="col-md-6 mb-3">
        <label for="id_comprobante_domicilio">Comprobante de Domicilio</label>
        {{ documentos_personales_form.comprobante_domicilio }}
        {% if documentos_personales_form.comprobante_domicilio.errors %}
          <div class="alert alert-danger">
            {% for error in documentos_personales_form.comprobante_domicilio.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <div class="col-md-6 mb-3">
        <label for="id_certificado_estudio">Certificado de Estudio</label>
        {{ documentos_personales_form.certificado_estudio }}
        {% if documentos_personales_form.certificado_estudio.errors %}
          <div class="alert alert-danger">
            {% for error in documentos_personales_form.certificado_estudio.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>

      <!-- Botón de envío -->
      <div class="col-md-12 text-center">
        <button type="submit" class="btn btn-success btn-block" style="background-color: #620b0b">
          Registrar Usuario <i class="fas fa-check-circle"></i>
        </button>
      </div>
    </div>
  </form>
</div>
{% endblock %}