form_app/urls.py
# login_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.form_view, name='formulario_aspirante'),  # Ruta principal del formulario
    path('registrar/', views.form_view, name='registrar_aspirante'),  # Registro del aspirante
    path('confirmacion/<int:aspirante_id>/', views.confirmacion, name='confirmacion'),
]

modulo_apec/urls.py
from django.urls import path
from . import views

app_name = 'modulo_apec'

urlpatterns = [
    path('home_apec/', views.home_view, name='home_apec'),
    path('vacantes/dashboards/observaciones/', views.observaciones_view, name='observaciones'),
    path('vacantes/dashboards/asignacion_vacantes/<int:servicio_id>/', views.asignacion_vacantes_view, name='asignacion_vacantes'),
    path('observacion/exitosa', views.exito_view, name='view_exito')
]

web_conafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static

from django.conf import settings
from django.conf.urls.static import static


# Vista para redirigir a login
def redirect_to_login(request):
    return redirect("login")  # Redirige a la URL de login definida en 'login_app.urls'


urlpatterns = [

    path('capacitacion/', include('modulo_capacitacion.urls')),
    path('modulo_educadores/', include('modulo_educadores.urls')),

    path('modulo_pagos/', include('modulo_pagos.urls')),  # Incluye las rutas de modulo_pagos
    path('modulo_calendario/', include('modulo_calendario.urls')),  # Incluye las rutas de modulo_calendario

    path("admin/", admin.site.urls),
    path('modulo_DECB/', include('modulo_DECB.urls')),  # Incluye las rutas del módulo DECB
    path(
        "", redirect_to_login
    ),  # Redirige a la página de login cuando acceden a la raíz
    path('formulario_aspirante/', include('form_app.urls')),
    path("login/", include("login_app.urls")),  # Redirige a las URLs de login
    path('api/', include('modulo_dot.api_urls')),  # Rutas exclusivas de la API
    path(
        "dot_section/", include(("modulo_dot.urls", "dot_home"), namespace="dot_home")
    ),
    path(
        "empleado_section/",
        include(
            ("home_empleado.urls", "dashboard_empleado"), namespace="dashboard_empleado"
        ),
    ),
    path(
        "coordinador_section/",
        include(
            ("modulo_coordinador.urls", "coordinador_home"),
            namespace="coordinador_home",
        ),
    ),
    path(
        "apec_section/",
        include(("modulo_apec.urls", "modulo_apec"), namespace="modulo_apec"),
    ),
    path(
        "dpe_section/",
        include(
            ("modulo_dpe.urls", "modulo_dpe"), 
            namespace="modulo_dpe"),
    ),
]


# Servir archivos de medios durante el desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modulo_apec/models.py
from django.db import models
from django.core.validators import MinValueValidator, RegexValidator
from django.utils import timezone

# Modelo para Estados
class Estado(models.Model):
    cv_estado = models.CharField(
        max_length=5,
        primary_key=True,
        verbose_name="Clave única del estado",
        validators=[RegexValidator(regex='^[A-Za-z0-9]+$', message="Solo se permiten letras y números.")]
    )
    nombre_estado = models.CharField(max_length=100, verbose_name="Nombre completo del estado")

    class Meta:
        db_table = "estado"

    def __str__(self):
        return self.nombre_estado


class Municipio(models.Model):
    cv_municipio = models.CharField(
        max_length=10,
        primary_key=True,
        verbose_name="Clave única del municipio",
        validators=[RegexValidator(regex='^[A-Za-z0-9]+$', message="Solo se permiten letras y números.")]
    )
    nombre_municipio = models.CharField(max_length=100, verbose_name="Nombre completo del municipio")
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, related_name="municipios", verbose_name="Estado al que pertenece", null=True, blank=True)

    class Meta:
        db_table = "municipio"

    def __str__(self):
        return self.nombre_municipio


# Modelo para Regiones
class Region(models.Model):
    cv_region = models.CharField(
        max_length=10,
        primary_key=True,
        verbose_name="Clave única de la región",
        validators=[RegexValidator(regex='^[A-Za-z0-9]+$', message="Solo se permiten letras y números.")]
    )
    nombre_region = models.CharField(max_length=100, verbose_name="Nombre completo de la región")
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, related_name="regiones", verbose_name="Estado al que pertenece", null=True, blank=True)
    municipios_region = models.CharField(max_length=255, verbose_name="Municipios que pertenecen a la región", null=True, blank=True)

    class Meta:
        db_table = "region"

    def __str__(self):
        return self.nombre_region


# Modelo para Microrregiones
class Microrregion(models.Model):
    cv_microrregion = models.CharField(
        max_length=20,
        primary_key=True,
        verbose_name="Clave única de la microrregión",
        validators=[RegexValidator(regex='^[A-Za-z0-9]+$', message="Solo se permiten letras y números.")]
    )
    nombre_microrregion = models.CharField(max_length=100, verbose_name="Nombre completo de la microrregión")
    region = models.ForeignKey(
        Region, 
        on_delete=models.CASCADE, 
        related_name="microrregiones", 
        verbose_name="Región a la que pertenece",
        null=True, blank=True
    )
    class Meta:
        db_table = "microrregion"

    def __str__(self):
        return self.nombre_microrregion


# Modelo para Comunidades
class Comunidad(models.Model):
    cv_comunidad = models.CharField(
        max_length=20,
        primary_key=True,
        verbose_name="Clave única de la comunidad",
        validators=[RegexValidator(regex='^[A-Za-z0-9]+$', message="Solo se permiten letras y números.")]
    )
    nombre_comunidad = models.CharField(max_length=100, verbose_name="Nombre completo de la comunidad")
    microrregion = models.ForeignKey(
        Microrregion,
        on_delete=models.CASCADE,
        related_name="comunidades",
        verbose_name="Microrregión a la que pertenece",
        null=True, blank=True
    )
    contexto_comunidad = models.CharField(
        max_length=255,
        choices=[ 
            ('Sin asignar', 'Sin asignar'),
            ('Indígena', 'Indígena'),
            ('Mestizo', 'Mestizo'),
            ('Migrante', 'Migrante'),
            ('Circense', 'Circense'),
            ('Grupos Vulnerables', 'Grupos Vulnerables'),
            ('Excluidos del Sistema Regular', 'Excluidos del Sistema Regular')
        ], 
        default='Sin asignar',
        null=True, blank=True
    )
    tipo_servicio = models.TextField(verbose_name="Tipo de servicio educativo que se ofrece", null=True, blank=True)
    usuario = models.OneToOneField('modulo_dot.Usuario', on_delete=models.CASCADE, null=True, blank=True)
    estatus = models.CharField(
        max_length=8,
        choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')],
        verbose_name="Estado actual de la comunidad",
        null=True, blank=True
    )
    localizacion = models.FileField(
        upload_to='comunidades/', 
        verbose_name="Archivo asociado a la comunidad", 
        null=True, blank=True
    )

    class Meta:
        db_table = "comunidad"

    def __str__(self):
        return self.nombre_comunidad


class ApoyoGestion(models.Model):
    usuario = models.OneToOneField('modulo_dot.Usuario', on_delete=models.CASCADE, null=True, blank=True)
    nombre_servicio_educativo = models.CharField(max_length=255)
    numero_ec_asignado = models.IntegerField()
    meses_servicio = models.IntegerField()
    monto_apoyo_mensual = models.DecimalField(max_digits=10, decimal_places=2)
    presupuesto_total_periodo = models.DecimalField(max_digits=15, decimal_places=2)

    def calcular_presupuesto_total(self):
        return self.numero_ec_asignado * self.meses_servicio * self.monto_apoyo_mensual

    def save(self, *args, **kwargs):
        self.presupuesto_total_periodo = self.calcular_presupuesto_total()
        super(ApoyoGestion, self).save(*args, **kwargs)
    
    class Meta:
        db_table = "apoyo_gestion"
        
    def __str__(self):
        return f"{self.nombre_servicio_educativo} - EC: {self.numero_ec_asignado}"



class ServicioEducativo(models.Model):
    apoyo_gestion = models.ForeignKey(ApoyoGestion, on_delete=models.CASCADE, null=True, blank=True)
    comunidad_servicio = models.ForeignKey(Comunidad, on_delete=models.CASCADE, null=True, blank=True)
    clave_estado = models.CharField(max_length=255, null=True, blank=True)
    nombre_estado = models.CharField(max_length=255, default="Estado")
    clave_region = models.CharField(max_length=255, null=True, blank=True)
    nombre_region = models.CharField(max_length=255, default="Región")
    clave_microregion = models.CharField(max_length=255, default="Región")
    nombre_microregion = models.CharField(max_length=255)
    clave_comunidad = models.CharField(max_length=255)
    nombre_comunidad = models.CharField(max_length=255, default="Nombre genérico")
    clave_centro_trabajo = models.CharField(max_length=100, null=True, blank=True)
    nombre_escuela = models.CharField(max_length=255, null=True, blank=True)
    tipo_sede = models.CharField(max_length=255, null=True, blank=True)
    tipo_servicio = models.CharField(
        max_length=255,
        choices=[
            ("preescolar", "Preescolar"),
            ("primaria", "Primaria"),
            ("secundaria", "Secundaria")
        ], null=True, blank=True
    )
    nivel_escolar = models.CharField(
        max_length=255,
        choices=[
            ("primaria I", "Primaria I"),
            ("primaria II", "Primaria II"),
            ("primaria III", "Primaria III"),
            ("secundaria", "Secundaria"),
            ("inicial", "Inicial")
        ],
        null=True, blank=True
    )
    periodo_servicio = models.CharField(
        max_length=255,
        choices=[ 
            ('sin asignar', 'sin asignar'),
            ('2024-2025', '2024-2025'),
            ('2025-2026', '2025-2026')
        ], default='sin asignar',
        null=True, blank=True  # Hacerlo opcional
    )
    rol_vacante = models.CharField(
        max_length=10,
        choices=[  
            ("EC", "Educador Comunitario"),
            ("ECA", "Educador Comunitario de Acompañamiento Microrregional"),
            ("ECAR", "Educador Comunitario de Acompañamiento Regional"),
        ],
        null=True, blank=True  # Hacerlo opcional
    )

    # Nuevos campos
    cantidad_educadores_activos = models.IntegerField(default=0)  # Número de educadores activos
    cantidad_solicitudes = models.IntegerField(default=0)  # Número de solicitudes realizadas
    status = models.CharField(
        max_length=10,
        choices=[
            ("aprobado", "Aprobado"),
            ("rechazado", "Rechazado"),
            ("pendiente", "Pendiente")
        ],
        default="Pendiente",
        null=True, blank=True
    )

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super(ServicioEducativo, self).save(*args, **kwargs)
        if is_new:
            self.__handle_observacion()

    def __handle_observacion(self):
        Observacion.objects.create(
            servicio_educativo=self,
            fecha_creacion=timezone.now(),
        )
    
    class Meta:
        db_table = "servicio_educativo"

    def __str__(self):
        return f"{self.nombre_comunidad} - {self.nombre_region} ({self.clave_centro_trabajo})"



class Observacion(models.Model):
    servicio_educativo = models.ForeignKey(
        ServicioEducativo, on_delete=models.CASCADE, null=True, blank=True
    )
    fecha_creacion = models.DateField(null=True, blank=True)
    fecha = models.DateField(null=True, blank=True)
    comentario = models.TextField(null=True, blank=True)
    candidatos = models.ManyToManyField(
        'modulo_dot.Usuario', 
        blank=True, 
        related_name="observaciones"
    )

    class Meta:
        db_table = "observacion"

    def __str__(self):
        return f"Observación del servicio educativo: {self.servicio_educativo.clave_centro_trabajo}"
    

class DatosComplementarios(models.Model):
    id_SituacionEducativa = models.AutoField(primary_key=True)
    id_Usuario = models.ForeignKey('modulo_dot.Usuario', on_delete=models.SET_NULL, null=True, blank=True, related_name='datos_complementarios')
    situacionEducativa = models.CharField(max_length=100, null=True, blank=True)
    
    # Relación con Región, Microrregión, y otros detalles geográficos

modulo_apec/forms.py
from django import forms
from .models import Observacion

class ObservacionForm(forms.ModelForm):
    class Meta:
        model = Observacion
        fields = ['comentario']

modulo_apec/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from login_app.decorators import role_required
from .models import ServicioEducativo, Observacion
from .forms import ObservacionForm
from django.utils import timezone
from django.contrib import messages
from django.http import HttpResponse
from modulo_dot.models import Usuario

@login_required
@role_required('APEC')
def home_view(request):
    return render(request, 'home_apec/home_apec.html')


@login_required
@role_required('APEC')
def observaciones_view(request):
    servicios = ServicioEducativo.objects.all()

    if request.method == 'POST':
        servicio_id = request.POST.get('servicio_id')
        try:
            servicio = ServicioEducativo.objects.get(id=servicio_id)
        except ServicioEducativo.DoesNotExist:
            return HttpResponse("Servicio no encontrado", status=404)

        form = ObservacionForm(request.POST)
        if form.is_valid():
            observacion = form.save(commit=False)
            observacion.servicio_educativo = servicio
            observacion.fecha_creacion = timezone.now()
            observacion.save()

            # Redirigir a la página de asignación de vacantes
            return redirect('modulo_apec:asignacion_vacantes', servicio_id=servicio.id)
        else:
            return HttpResponse("Formulario no válido", status=400)

    return render(request, 'home_apec/dashboard_vacantes_apec.html', {'servicios': servicios})

@login_required
@role_required('APEC')
def asignacion_vacantes_view(request, servicio_id):
    servicio = get_object_or_404(ServicioEducativo, id=servicio_id)

    # Consulta optimizada con el nombre correcto del campo relacionado
    usuarios = Usuario.objects.filter(rol__in=['EC', 'ECA', 'ECAR']).select_related('datospersonales', 'aspirante__residencia')

    # Obtención de la observación asociada al servicio educativo
    observacion = Observacion.objects.filter(servicio_educativo=servicio).first()

    if request.method == 'POST':
        candidatos_ids = request.POST.getlist('candidatos')
        candidatos = Usuario.objects.filter(id__in=candidatos_ids).select_related('datospersonales', 'aspirante__residencia')

        comentario = request.POST.get('comentario')
        rol = request.POST.get('rol')
        ciclo = request.POST.get('ciclo')

        if observacion:
            observacion.comentario = comentario if comentario else observacion.comentario
            observacion.save()
        else:
            observacion = Observacion.objects.create(
                servicio_educativo=servicio,
                fecha_creacion=timezone.now(),
                comentario=comentario,
            )

        servicio.rol_vacante = rol if rol else 'NP'
        servicio.periodo_servicio = ciclo if ciclo else 'Sin asignar'
        servicio.save()

        if candidatos:
            observacion.candidatos.set(candidatos)
            observacion.save()

        
        return redirect('modulo_apec:view_exito')

    return render(
        request,
        'home_apec/asignacion_vacantes.html',
        {'servicio': servicio, 'usuarios': usuarios}
    )

def exito_view(request):
    return render(request, 'home_apec/mensaje_exito.html')

modulo_apec/templates/home_apec/asignacion_vacantes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Asignación de candidatos a servicio educativo.">
    <meta name="author" content="Tu Nombre">
    <title>Asignación de Candidatos a Servicio Educativo</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        :root {
            --primary-color: #620b0b;
            --primary-color-hover: #631818e3;
            --secondary-color: #f8faeb;
            --text-color: #333;
        }
        body {
            font-family: 'Roboto', sans-serif;
            background-color: var(--secondary-color);
        }
        .header-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }
        h1 {
            color: var(--text-color);
            margin: 0;
        }
        .btn-custom {
            background-color: var(--primary-color);
            color: white;
            border-radius: 5px;
            transition: background-color 0.3s;
        }
        .btn-custom:hover {
            background-color: var(--primary-color-hover);
            color: white;
        }
        .form-container {
            background-color: white;
            padding: 20px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <div class="header-container">
            <h1>Asignación de Candidatos a Servicio Educativo: {{ servicio.nombre_comunidad }}</h1>
            <a href="{% url 'modulo_apec:home_apec' %}" class="btn btn-custom">Menú Promoción</a>
        </div>

        <!-- Mensajes Flash -->
        {% if messages %}
            <div class="alert alert-success">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <div class="form-container">
            <h3>Formulario de Observación</h3>

            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
            
                <!-- Campo de comentario -->
                <div class="form-group">
                    <label for="id_comentario">Comentario:</label>
                    <textarea name="comentario" id="id_comentario" rows="4" class="form-control"></textarea>
                </div>
            
                <!-- Campo de selección de candidatos -->
                <!-- Campo de selección de candidatos -->
                <div class="form-group">
                    <label for="id_candidatos">Seleccionar Candidatos <span class="text-danger">*</span>:</label>
                    <select name="candidatos" id="id_candidatos" class="form-control" multiple required>
                        {% for usuario in usuarios %}
                            <option value="{{ usuario.id }}">
                                {{ usuario.usuario }} {{ usuario.rol }} 
                                {{ usuario.datospersonales.nombre }}
                                {{ usuario.datospersonales.apellidopa}}
                                {{ usuario.datospersonales.apellidoma}}
                                {{ usuario.aspirante.residencia.calle }}, 
                                {{ usuario.aspirante.residencia.colonia }},
                                {{ usuario.aspirante.residencia.municipio_alcaldia }},
                                {{ usuario.aspirante.residencia.estado }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            
                <!-- Botón para guardar y asignar candidatos -->
                <button type="submit" class="btn btn-primary" style="background-color: #620b0b;">Guardar Observación y Asignar Candidatos</button>
            </form>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

modulo_apec/templates/home_apec/dashboard_vacantes_apec.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Listado de servicios educativos vacantes con detalles completos sobre las regiones, roles y contexto.">
    <meta name="author" content="Tu Nombre">
    <title>Servicios Educativos Vacantes Observaciones</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        :root {
            --primary-color: #620b0b;
            --primary-color-hover: hsla(0, 61%, 24%, 0.89);
            --secondary-color: #f8faeb;
            --text-color: #333;
            --header-bg-color: #f8faeb;
            --header-text-color: #f8faeb;
        }
        body {
            font-family: 'Roboto', sans-serif;
            background-color: var(--secondary-color);
        }
        h1 {
            color: var(--text-color);
            font-size: 1.5rem;
        }
        .btn-custom {
            background-color: var(--primary-color);
            color: white;
            border-radius: 5px;
            font-size: 0.8rem;
            padding: 5px 10px;
        }
        .btn-custom:hover {
            background-color: var(--primary-color-hover);
            color: white;
        }
        .table-container {
            overflow-x: auto;
        }
        .table {
            table-layout: fixed;
            width: 100%;
            font-size: 0.75rem;
        }
        th, td {
            text-align: center;
            padding: 5px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        th {
            background-color: var(--primary-color);
            color: white;
        }
        td {
            background-color: var(--secondary-color);
        }
        .header-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="container mt-3">
        <div class="header-container">
            <h1>Servicios Educativos Vacantes</h1>
            <a href="{% url 'modulo_apec:home_apec' %}" class="btn btn-custom" aria-label="Ir al menú principal">Menú Promoción</a>
        </div>
        <div class="table-container">
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th>CvEstado</th>
                        <th>Estado</th>
                        <th>Cv Región</th>
                        <th>Región</th>
                        <th>CvMicrorregión</th>
                        <th>Microrregión</th>
                        <th>CvComunidad</th>
                        <th>Comunidad</th>
                        <th>Rol Vacante</th>
                        <th>Tipo Servicio</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for servicio in servicios %}
                    <tr>
                        <td>{{ servicio.clave_estado }}</td>
                        <td>{{ servicio.nombre_estado }}</td>
                        <td>{{ servicio.clave_region }}</td>
                        <td>{{ servicio.nombre_region }}</td>
                        <td>{{ servicio.clave_microregion }}</td>
                        <td>{{ servicio.nombre_microregion }}</td>
                        <td>{{ servicio.clave_comunidad }}</td>
                        <td>{{ servicio.nombre_comunidad }}</td>
                        <td>{{ servicio.rol_vacante }}</td>
                        <td>{{ servicio.rol_vacante  }}</td>
                        <td>
                            <form method="POST" action="{% url 'modulo_apec:observaciones' %}">
                                {% csrf_token %}
                                <input type="hidden" name="servicio_id" value="{{ servicio.id }}">
                                <button type="submit" class="btn btn-custom">Asignar</button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

modulo_apec/templates/home_apec/home_apec.html
{% extends "base.html" %} <!-- Extiende una plantilla base para consistencia en el diseño -->

{% block title %}Home Director de Operaciones{% endblock %}

{% block content %}
<div class="container mt-5">
  <h2 class="mb-4 text-center">Home Director de Operaciones</h2>
  <p class="text-center">Bienvenido Director de Operaciones!</p>

  <div class="row text-center">
    <!-- Botón Crear y enviar plan de captación -->
    <div class="col-md-5 mb-4">
      <a href="{% url 'modulo_apec:observaciones' %}" class="btn btn-primary btn-block">
      <i class="fas fa-file-signature"></i> Observaciones y Recomendacion de Educadores
      </a>
    </div>

</div>
{% endblock %}

modulo_apec/templates/home_apec/mensaje_exito.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Operación Exitosa</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">¡Operación Exitosa!</h4>
            <p>La acción que realizaste se completó con éxito. Los cambios han sido guardados correctamente.</p>
            <hr>
            <p class="mb-0">Puedes continuar con otras tareas o volver a la vista principal.</p>
        </div>
        <div class="text-center">
            <a href="{% url 'modulo_apec:observaciones' %}" class="btn btn-primary" style="background-color: #620b0b;" >Volver al inicio</a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>